class CourseInfo:
    def __init__(self):
        self.section = ""
        self.description = ""
        self.room = ""
        self.quarter = ""
        self.year = ""
        self.meeting_days = ""
        self.start_time = ""
        self.end_time = ""
        self.current_size = ""
        self.max_size = ""
        self.needs_add_code = ""
        self.lower_credits = ""
        self.upper_credits = ""
        self.is_dual = ""
        self.type = ""
        self.gen_ed_marker = ""
        self.is_crnc = ""
        self.course_fee = ""
